#pragma config(Motor,  motorB,          rightMotor,         tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,          tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "JoystickDriver.c"

task main()
{
while (1==1)
	{
	getJoystickSettings(joystick);
		motor[leftMotor] = joystick.joy1_y1;
		motor[rightMotor] = joystick.joy1_y2;
	}
}
